In [2]:
%load_ext autoreload
%autoreload 2

from src import physics 
from src import acoplamento 
import numpy as np
from src import dedo

In [13]:
F = np.array([-3, 3])
rp = np.array([0.3, 0.3, 0.3])
rs = np.array([0.2, 0.2, 0])
l = np.array([1, 1, 1])
teta = np.array([10, 10, 10])

dedo_1 = dedo.Dedo(rp, rs, l, teta, 2)

In [14]:
T = physics.calc_tensao_dedo(F, dedo_1.rp, dedo_1.rs, dedo_1.l, dedo_1.teta)
print(T)

[6.77360058 3.01048915]


In [5]:
alpha = np.array([0, 0, 0.1, 0])

ativado = acoplamento.ativacao_tensoes(alpha)
print(ativado)

[0.01  0.035 0.1   0.035]


In [10]:
F1 = physics.calc_forca_dedo(np.sum(T), dedo_1.rp, dedo_1.rs, dedo_1.l, dedo_1.teta, [3, -3])
print(F1)

[-3.  3.]


In [ ]:
dado = acoplamento.evolucao_pinca(100, dedo_1, alpha, 1)
print(dado)

(array([395.95363265,   0.        ,   0.        ,   0.        ]), array([395.95363265,  98.98840816,  39.59536327,  19.79768163]), array([  0., 100.]), 18)


In [90]:
dado = acoplamento.evolucao_pinca(100, dedo_1, alpha, 1)
print(dado)

(array([  0.        , 395.95363265,   0.        ,   0.        ]), array([ 79.19072653, 395.95363265, 158.38145306,  59.3930449 ]), array([  0., 100.]), 18)


In [93]:
dado = acoplamento.evolucao_pinca(100, dedo_1, alpha, 1)
print(dado)

(array([  0.        ,   0.        , 395.95363265,   0.        ]), array([ 39.59536327, 138.58377143, 395.95363265, 138.58377143]), array([  0., 100.]), 18)
